-- =====================================================================
-- CMPG 311 | Group 8 | Bus Ticket Booking System
-- PHASE 3: COMPLETE RUBRIC QUERIES (52 Marks)
-- Database: PostgreSQL
-- =====================================================================

-- =====================================================================
-- 1. QUERIES BASED ON COMPANY INFORMATION REQUIREMENTS (10 Marks)
-- =====================================================================

-- 1.1 Find all available schedules for a specific route
SELECT s.id, r.departure_location, r.destination, s.departure_time, s.arrival_time, 
       b.bus_type, b.registration_number, s.travel_date
FROM core_schedule s
JOIN core_route r ON s.route_id = r.id
JOIN core_bus b ON s.bus_id = b.id
WHERE r.departure_location = 'Johannesburg' 
  AND r.destination = 'Durban'
  AND s.departure_time > NOW()
ORDER BY s.departure_time;

-- 1.2 View all bookings for a specific passenger
SELECT b.id AS booking_id, r.departure_location, r.destination, 
       s.departure_time, b.booking_status, b.total_fare, b.booking_date
FROM core_booking b
JOIN core_schedule s ON b.schedule_id = s.id
JOIN core_route r ON s.route_id = r.id
WHERE b.user_id = 1
ORDER BY b.booking_date DESC;

-- 1.3 Total revenue generated by the system
SELECT COALESCE(SUM(amount), 0) AS total_revenue,
       COUNT(*) AS total_payments
FROM core_payment
WHERE payment_status = 'PAID';

-- 1.4 List all unresolved complaints
SELECT c.id, u.username, u.email, c.description, c.date_submitted, c.resolution_status
FROM core_complaint c
JOIN core_user u ON c.user_id = u.id
WHERE c.resolution_status != 'resolved'
ORDER BY c.date_submitted ASC;

-- 1.5 View all schedules for a specific date
SELECT s.id, r.departure_location, r.destination, s.departure_time, 
       b.registration_number, b.capacity
FROM core_schedule s
JOIN core_route r ON s.route_id = r.id
JOIN core_bus b ON s.bus_id = b.id
WHERE s.travel_date = CURRENT_DATE + INTERVAL '1 day'
ORDER BY s.departure_time;

-- 1.6 Count bookings per route (popularity report)
SELECT r.departure_location, r.destination, COUNT(b.id) AS total_bookings
FROM core_route r
LEFT JOIN core_schedule s ON r.id = s.route_id
LEFT JOIN core_booking b ON s.id = b.schedule_id AND b.booking_status = 'BOOKED'
GROUP BY r.id, r.departure_location, r.destination
ORDER BY total_bookings DESC;

-- 1.7 Find passengers with their next of kin details
SELECT u.username, u.first_name, u.last_name, u.phone_number,
       nk.kin_fullname, nk.contact_number
FROM core_user u
LEFT JOIN core_nextofkin nk ON u.id = nk.user_id
ORDER BY u.last_name;

-- 1.8 View all active buses
SELECT id, bus_type, capacity, registration_number
FROM core_bus
WHERE id IN (SELECT DISTINCT bus_id FROM core_schedule WHERE departure_time > NOW());

-- 1.9 Payment summary by method
SELECT payment_method, COUNT(*) AS count, SUM(amount) AS total
FROM core_payment
WHERE payment_status = 'PAID'
GROUP BY payment_method;

-- 1.10 Users who have made bookings but no payments
SELECT DISTINCT u.username, u.email
FROM core_user u
JOIN core_booking b ON u.id = b.user_id
WHERE b.booking_status = 'BOOKED'
  AND b.id NOT IN (SELECT booking_id FROM core_payment WHERE payment_status = 'PAID');


-- =====================================================================
-- 2. QUERY LIMITATIONS (Rows & Columns) (4 Marks)
-- =====================================================================

-- 2.1 Limit rows returned (first 10 users)
SELECT id, username, email, first_name, last_name, account_status
FROM core_user
LIMIT 10;

-- 2.2 Limit both rows and specific columns (5 most recent bookings)
SELECT id AS booking_id, booking_status, booking_date, total_fare
FROM core_booking
ORDER BY booking_date DESC
LIMIT 5;

-- 2.3 Pagination-style: skip first 5, show next 5
SELECT id, username, email
FROM core_user
ORDER BY id
LIMIT 5 OFFSET 5;


-- =====================================================================
-- 3. SORTING OPERATIONS (4 Marks)
-- =====================================================================

-- 3.1 Sort schedules by departure time (ascending)
SELECT id, departure_time, arrival_time, travel_date
FROM core_schedule
ORDER BY departure_time ASC;

-- 3.2 Sort users alphabetically by last name
SELECT id, first_name, last_name, email
FROM core_user
ORDER BY last_name ASC, first_name ASC;

-- 3.3 Sort payments by amount (highest first)
SELECT id, booking_id, amount, payment_method, payment_status, payment_date
FROM core_payment
ORDER BY amount DESC;

-- 3.4 Sort complaints by date submitted (oldest first)
SELECT id, user_id, description, date_submitted, resolution_status
FROM core_complaint
ORDER BY date_submitted ASC;


-- =====================================================================
-- 4. USAGE OF LIKE, AND, OR OPERATORS (4 Marks)
-- =====================================================================

-- 4.1 LIKE: Find users whose first name starts with 'S'
SELECT id, first_name, last_name, email
FROM core_user
WHERE first_name LIKE 'S%';

-- 4.2 LIKE: Find routes containing 'burg' in destination
SELECT id, departure_location, destination, route_distance
FROM core_route
WHERE destination LIKE '%burg%' OR departure_location LIKE '%burg%';

-- 4.3 AND: Find confirmed bookings for a specific schedule
SELECT id, user_id, schedule_id, booking_status, total_fare
FROM core_booking
WHERE booking_status = 'BOOKED' AND schedule_id = 1;

-- 4.4 OR: Find bookings that are either pending or cancelled
SELECT id, user_id, booking_status, booking_date
FROM core_booking
WHERE booking_status = 'PENDING' OR booking_status = 'CANCELLED';

-- 4.5 LIKE + AND: Active users with email containing 'test'
SELECT id, username, email, account_status
FROM core_user
WHERE email LIKE '%@test%' AND account_status = 'active';


-- =====================================================================
-- 5. VARIABLES & CHARACTER FUNCTIONS (4 Marks)
-- =====================================================================

-- 5.1 UPPER and LOWER case functions
SELECT 
    id,
    UPPER(first_name) AS first_name_upper,
    LOWER(last_name) AS last_name_lower,
    username
FROM core_user
LIMIT 10;

-- 5.2 CONCATENATION: Full name
SELECT 
    id,
    first_name || ' ' || last_name AS full_name,
    email
FROM core_user;

-- 5.3 SUBSTRING: Extract email domain
SELECT 
    id,
    email,
    SUBSTRING(email FROM POSITION('@' IN email) + 1) AS email_domain
FROM core_user;

-- 5.4 LENGTH function
SELECT 
    id,
    username,
    LENGTH(username) AS username_length,
    LENGTH(email) AS email_length
FROM core_user;

-- 5.5 TRIM and INITCAP
SELECT 
    id,
    TRIM(first_name) AS trimmed_name,
    INITCAP(first_name || ' ' || last_name) AS display_name
FROM core_user
LIMIT 10;


-- =====================================================================
-- 6. ROUNDING / TRUNCATION (4 Marks)
-- =====================================================================

-- 6.1 ROUND payment amounts to 2 decimal places
SELECT 
    id,
    amount,
    ROUND(amount, 2) AS rounded_amount,
    TRUNC(amount) AS truncated_amount
FROM core_payment;

-- 6.2 ROUND average fare per route
SELECT 
    r.departure_location,
    r.destination,
    ROUND(AVG(b.total_fare), 2) AS avg_fare_rounded,
    TRUNC(AVG(b.total_fare)) AS avg_fare_truncated
FROM core_route r
JOIN core_schedule s ON r.id = s.route_id
JOIN core_booking b ON s.id = b.schedule_id
GROUP BY r.id, r.departure_location, r.destination;

-- 6.3 CEIL and FLOOR functions
SELECT 
    id,
    capacity,
    CEIL(capacity * 0.75) AS rounded_up_75_percent,
    FLOOR(capacity * 0.25) AS rounded_down_25_percent
FROM core_bus;

-- 6.4 ROUND route distances
SELECT 
    id,
    departure_location,
    destination,
    route_distance,
    ROUND(route_distance, 0) AS rounded_km,
    TRUNC(route_distance) AS truncated_km
FROM core_route;


-- =====================================================================
-- 7. DATE FUNCTIONS (4 Marks)
-- =====================================================================

-- 7.1 Current date and time
SELECT 
    NOW() AS current_datetime,
    CURRENT_DATE AS today,
    CURRENT_TIME AS current_time;

-- 7.2 Extract day, month, year from booking date
SELECT 
    id,
    booking_date,
    EXTRACT(DAY FROM booking_date) AS booking_day,
    EXTRACT(MONTH FROM booking_date) AS booking_month,
    EXTRACT(YEAR FROM booking_date) AS booking_year
FROM core_booking;

-- 7.3 Days until departure for upcoming schedules
SELECT 
    id,
    departure_time,
    travel_date,
    EXTRACT(DAY FROM (departure_time - NOW())) AS days_until_departure,
    EXTRACT(HOUR FROM (departure_time - NOW())) AS hours_until_departure
FROM core_schedule
WHERE departure_time > NOW()
ORDER BY departure_time;

-- 7.4 Date formatting with TO_CHAR
SELECT 
    id,
    TO_CHAR(booking_date, 'DD Mon YYYY') AS formatted_date,
    TO_CHAR(booking_date, 'Day, DD Month YYYY') AS full_date
FROM core_booking
LIMIT 5;

-- 7.5 Date arithmetic (add/subtract intervals)
SELECT 
    id,
    departure_time,
    departure_time + INTERVAL '2 hours' AS two_hours_later,
    departure_time - INTERVAL '30 minutes' AS thirty_min_before
FROM core_schedule
LIMIT 5;

-- 7.6 AGE function (time between two dates)
SELECT 
    c.id,
    c.date_submitted,
    COALESCE(c.date_resolved, NOW()) AS resolved_or_now,
    AGE(COALESCE(c.date_resolved, NOW()), c.date_submitted) AS complaint_age
FROM core_complaint c;


-- =====================================================================
-- 8. AGGREGATE FUNCTIONS (4 Marks)
-- =====================================================================

-- 8.1 COUNT, SUM, AVG, MAX, MIN on payments
SELECT 
    COUNT(*) AS total_payments,
    SUM(amount) AS total_revenue,
    AVG(amount) AS average_payment,
    MAX(amount) AS largest_payment,
    MIN(amount) AS smallest_payment
FROM core_payment
WHERE payment_status = 'PAID';

-- 8.2 COUNT bookings per user
SELECT 
    u.username,
    COUNT(b.id) AS booking_count,
    COALESCE(SUM(b.total_fare), 0) AS total_spent,
    COALESCE(AVG(b.total_fare), 0) AS avg_fare
FROM core_user u
LEFT JOIN core_booking b ON u.id = b.user_id AND b.booking_status = 'BOOKED'
GROUP BY u.id, u.username
ORDER BY booking_count DESC;

-- 8.3 COUNT tickets per schedule
SELECT 
    s.id AS schedule_id,
    r.departure_location,
    r.destination,
    COUNT(t.id) AS tickets_issued,
    b.capacity AS total_capacity
FROM core_schedule s
JOIN core_route r ON s.route_id = r.id
JOIN core_bus b ON s.bus_id = b.id
LEFT JOIN core_booking bk ON s.id = bk.schedule_id
LEFT JOIN core_ticket t ON bk.id = t.booking_id AND t.ticket_status = 'ACTIVE'
GROUP BY s.id, r.departure_location, r.destination, b.capacity
ORDER BY tickets_issued DESC;


-- =====================================================================
-- 9. GROUP BY & HAVING CLAUSES (4 Marks)
-- =====================================================================

-- 9.1 Routes with more than 1 booking
SELECT 
    r.departure_location,
    r.destination,
    COUNT(b.id) AS booking_count
FROM core_route r
LEFT JOIN core_schedule s ON r.id = s.route_id
LEFT JOIN core_booking b ON s.id = b.schedule_id
GROUP BY r.id, r.departure_location, r.destination
HAVING COUNT(b.id) > 1
ORDER BY booking_count DESC;

-- 9.2 Users who have spent more than R300
SELECT 
    u.username,
    u.first_name || ' ' || u.last_name AS full_name,
    SUM(b.total_fare) AS total_spent
FROM core_user u
JOIN core_booking b ON u.id = b.user_id
WHERE b.booking_status = 'BOOKED'
GROUP BY u.id, u.username, u.first_name, u.last_name
HAVING SUM(b.total_fare) > 300
ORDER BY total_spent DESC;

-- 9.3 Payment methods used more than once
SELECT 
    payment_method,
    COUNT(*) AS times_used,
    SUM(amount) AS total_collected
FROM core_payment
WHERE payment_status = 'PAID'
GROUP BY payment_method
HAVING COUNT(*) > 1
ORDER BY times_used DESC;

-- 9.4 Schedules with more than 2 tickets booked
SELECT 
    s.id AS schedule_id,
    r.departure_location || ' → ' || r.destination AS route,
    COUNT(t.id) AS tickets_booked
FROM core_schedule s
JOIN core_route r ON s.route_id = r.id
JOIN core_booking b ON s.id = b.schedule_id
JOIN core_ticket t ON b.id = t.booking_id AND t.ticket_status = 'ACTIVE'
GROUP BY s.id, r.departure_location, r.destination
HAVING COUNT(t.id) > 2
ORDER BY tickets_booked DESC;


-- =====================================================================
-- 10. JOINS EXECUTED CORRECTLY (5 Marks)
-- =====================================================================

-- 10.1 INNER JOIN: Complete booking details with passenger info
SELECT 
    b.id AS booking_id,
    u.username,
    u.first_name || ' ' || u.last_name AS passenger,
    r.departure_location,
    r.destination,
    s.departure_time,
    s.arrival_time,
    b.booking_status,
    b.total_fare
FROM core_booking b
JOIN core_user u ON b.user_id = u.id
JOIN core_schedule s ON b.schedule_id = s.id
JOIN core_route r ON s.route_id = r.id
ORDER BY b.booking_date DESC;

-- 10.2 LEFT JOIN: All users with their bookings (including users with no bookings)
SELECT 
    u.id,
    u.username,
    u.email,
    COUNT(b.id) AS total_bookings
FROM core_user u
LEFT JOIN core_booking b ON u.id = b.user_id
GROUP BY u.id, u.username, u.email
ORDER BY total_bookings DESC;

-- 10.3 Multi-table JOIN: Booking + Payment + Ticket
SELECT 
    b.id AS booking_id,
    u.username,
    t.seat_number,
    t.ticket_status,
    p.amount AS payment_amount,
    p.payment_method,
    p.payment_status
FROM core_booking b
JOIN core_user u ON b.user_id = u.id
JOIN core_ticket t ON b.id = t.booking_id
LEFT JOIN core_payment p ON b.id = p.booking_id
ORDER BY b.id;

-- 10.4 JOIN with schedule, route, and bus
SELECT 
    s.id AS schedule_id,
    r.departure_location || ' → ' || r.destination AS route,
    b.registration_number AS bus,
    b.bus_type,
    s.departure_time,
    s.travel_date,
    b.capacity,
    COUNT(t.id) AS booked_seats
FROM core_schedule s
JOIN core_route r ON s.route_id = r.id
JOIN core_bus b ON s.bus_id = b.id
LEFT JOIN core_booking bk ON s.id = bk.schedule_id AND bk.booking_status = 'BOOKED'
LEFT JOIN core_ticket t ON bk.id = t.booking_id AND t.ticket_status = 'ACTIVE'
GROUP BY s.id, r.departure_location, r.destination, b.registration_number, 
         b.bus_type, s.departure_time, s.travel_date, b.capacity
ORDER BY s.departure_time;

-- 10.5 Self-referencing JOIN: Users assigned roles by other users
SELECT 
    u1.username AS assigned_user,
    r.role_name,
    u2.username AS assigned_by_admin,
    ur.assigned_date
FROM core_userrole ur
JOIN core_user u1 ON ur.user_id = u1.id
JOIN core_role r ON ur.role_id = r.id
LEFT JOIN core_user u2 ON ur.assigned_by_id = u2.id
ORDER BY ur.assigned_date DESC;


-- =====================================================================
-- 11. SUB-QUERIES USED EFFECTIVELY (5 Marks)
-- =====================================================================

-- 11.1 Subquery in WHERE: Users who have made at least one booking
SELECT id, username, email, first_name, last_name
FROM core_user
WHERE id IN (SELECT DISTINCT user_id FROM core_booking);

-- 11.2 Subquery with NOT IN: Users who have NEVER made a booking
SELECT id, username, email
FROM core_user
WHERE id NOT IN (SELECT DISTINCT user_id FROM core_booking);

-- 11.3 Subquery with EXISTS: Routes that have schedules
SELECT id, departure_location, destination
FROM core_route r
WHERE EXISTS (SELECT 1 FROM core_schedule s WHERE s.route_id = r.id);

-- 11.4 Subquery in SELECT: Average fare compared to overall average
SELECT 
    b.id,
    b.total_fare,
    (SELECT ROUND(AVG(total_fare), 2) FROM core_booking) AS overall_avg_fare,
    ROUND(b.total_fare - (SELECT AVG(total_fare) FROM core_booking), 2) AS difference_from_avg
FROM core_booking b
LIMIT 10;

-- 11.5 Correlated subquery: Users who spent more than average
SELECT 
    u.username,
    SUM(b.total_fare) AS total_spent
FROM core_user u
JOIN core_booking b ON u.id = b.user_id
GROUP BY u.id, u.username
HAVING SUM(b.total_fare) > (SELECT AVG(total_fare) FROM core_booking);

-- 11.6 Subquery in FROM: Derived table for analytics
SELECT 
    route_stats.departure_location,
    route_stats.destination,
    route_stats.booking_count,
    route_stats.avg_fare
FROM (
    SELECT 
        r.departure_location,
        r.destination,
        COUNT(b.id) AS booking_count,
        ROUND(AVG(b.total_fare), 2) AS avg_fare
    FROM core_route r
    JOIN core_schedule s ON r.id = s.route_id
    JOIN core_booking b ON s.id = b.schedule_id
    WHERE b.booking_status = 'BOOKED'
    GROUP BY r.id, r.departure_location, r.destination
) AS route_stats
WHERE route_stats.booking_count > 1
ORDER BY route_stats.booking_count DESC;